'use strict';
const $=id=>document.getElementById(id);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let db, records=[], editing={weight:null,workout:null};
const say=t=>$('status').textContent=t;
function tab(name){document.querySelectorAll('section').forEach(s=>s.hidden=s.id!==name);document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===name)));}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function transaction(mode,action){return new Promise((resolve,reject)=>{const tx=db.transaction('entries',mode);action(tx.objectStore('entries'));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Storage unavailable'));});}
async function refresh(){records=await new Promise((resolve,reject)=>{const req=db.transaction('entries').objectStore('entries').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});render();}
function reset(type){$(type+'-form').reset();$(type+'-date').value=today();editing[type]=null;$(type+'-title').textContent=type==='weight'?'Log your weight':'Log an exercise';$(type+'-form').querySelector('.cancel').hidden=true;}
function edit(r){editing[r.type]=r.id;$(r.type+'-date').value=r.date;$(r.type+'-note').value=r.note;if(r.type==='weight')$('weight-value').value=r.value;else{ $('exercise').value=r.exercise;$('sets').value=r.sets;$('reps').value=r.reps;$('load').value=r.load;}$(r.type+'-title').textContent=r.type==='weight'?'Edit weight':'Edit exercise';$(r.type+'-form').querySelector('.cancel').hidden=false;tab(r.type);window.scrollTo({top:0,behavior:'smooth'});}
function entry(r){const el=document.createElement('div');el.className='entry';const title=document.createElement('strong');title.textContent=r.type==='weight'?`${r.value.toFixed(1)} kg`:`${r.exercise} · ${r.sets} × ${r.reps} · ${r.load} kg`;const date=document.createElement('small');date.textContent=new Date(r.date+'T12:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});el.append(title,date);if(r.note){const note=document.createElement('small');note.textContent=r.note;el.append(note)}const actions=document.createElement('div');actions.className='actions';const e=document.createElement('button');e.className='muted';e.textContent='Edit';e.onclick=()=>edit(r);const d=document.createElement('button');d.className='danger';d.textContent='Delete';d.onclick=async()=>{if(!confirm('Delete this entry?'))return;try{await transaction('readwrite',s=>s.delete(r.id));if(editing[r.type]===r.id)reset(r.type);await refresh();say('Entry deleted.')}catch{say('Could not delete the entry.')}};actions.append(e,d);el.append(actions);return el;}
function list(id,items){const parent=$(id);parent.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='empty';p.textContent='No entries yet.';parent.append(p)}else items.forEach(r=>parent.append(entry(r)));}
function render(){const sorted=[...records].sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created);const weights=sorted.filter(r=>r.type==='weight').reverse();$('latest').textContent=weights.length?weights.at(-1).value.toFixed(1)+' kg':'—';const delta=weights.length?weights.at(-1).value-weights[0].value:0;$('change').textContent=weights.length>1?`${delta>0?'+':''}${delta.toFixed(1)} kg`:'—';list('entries',sorted.filter(r=>$('history-filter').value==='all'||r.type===$('history-filter').value));list('today',sorted.filter(r=>r.type==='workout'&&r.date===today()));chart(weights);}
function chart(weights){const host=$('chart');host.replaceChildren();if(weights.length<2){const p=document.createElement('p');p.className='empty';p.textContent='Add two weight entries to see your trend.';host.append(p);return;}const data=weights.slice(-30),min=Math.min(...data.map(r=>r.value))-0.5,max=Math.max(...data.map(r=>r.value))+0.5;const times=data.map(r=>new Date(r.date+'T12:00:00').getTime()),range=times.at(-1)-times[0];const points=data.map((r,i)=>[range?35+(times[i]-times[0])/range*330:35+i/(data.length-1)*330,120-(r.value-min)/(max-min)*100]);const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 400 160');svg.setAttribute('role','img');svg.setAttribute('aria-label','Weight trend for the last 30 entries');const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.map(p=>p.join(',')).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#739439');line.setAttribute('stroke-width','3');svg.append(line);points.forEach(p=>{const c=document.createElementNS(ns,'circle');c.setAttribute('cx',p[0]);c.setAttribute('cy',p[1]);c.setAttribute('r',4);c.setAttribute('fill','#163528');svg.append(c)});[[`${max.toFixed(1)} kg`,5,15],[`${min.toFixed(1)} kg`,5,140],[data[0].date,35,158],[data.at(-1).date,290,158]].forEach(([value,x,y])=>{const t=document.createElementNS(ns,'text');t.textContent=value;t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('font-size','11');t.setAttribute('fill','#64756b');svg.append(t)});host.append(svg);}
for(const type of ['weight','workout']){$(type+'-form').querySelector('.cancel').onclick=()=>reset(type);$(type+'-form').onsubmit=async e=>{e.preventDefault();if(!db){say('Local storage is unavailable.');return;}const button=e.target.querySelector('button');button.disabled=true;const old=records.find(r=>r.id===editing[type]);const r={id:editing[type]||crypto.randomUUID(),type,date:$(type+'-date').value,note:$(type+'-note').value.trim(),created:old?.created||Date.now()};if(type==='weight')r.value=Number($('weight-value').value);else Object.assign(r,{exercise:$('exercise').value.trim(),sets:Number($('sets').value),reps:Number($('reps').value),load:Number($('load').value)});try{if(type==='workout'&&!r.exercise)throw Error('Enter an exercise name.');await transaction('readwrite',s=>s.put(r));reset(type);await refresh();say('Saved.');}catch(err){say(err.message==='Enter an exercise name.'?err.message:'Could not save. Check whether browser storage is available.');}finally{button.disabled=false;}};reset(type);}
$('history-filter').onchange=render;
const open=indexedDB.open('my-fitness',1);open.onupgradeneeded=()=>open.result.createObjectStore('entries',{keyPath:'id'});open.onsuccess=async()=>{db=open.result;try{await refresh()}catch{say('Could not read your entries.')}};open.onerror=()=>say('Local storage is unavailable in this browser.');
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>say('Offline setup unavailable; the app still works online.'));
