'use strict';
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID();
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let db,entries=[],sessions=[],routines=[],active=null,weightEdit=null,saveChain=Promise.resolve();
const say=t=>$('status').textContent=t;
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function button(text,cls,action){const b=node('button',text,cls);b.type='button';b.onclick=action;return b;}
function tx(store,mode,fn){return new Promise((resolve,reject)=>{const t=db.transaction(store,mode);fn(t.objectStore(store));t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Storage unavailable'));});}
function all(store){return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function refresh(){[entries,sessions,routines]=await Promise.all(['entries','sessions','routines'].map(all));render();}
function tab(name){document.querySelectorAll('main>section').forEach(s=>s.hidden=s.id!==name);document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===name)));}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function saveDraft(){const snapshot=active?structuredClone(active):null;saveChain=saveChain.catch(()=>{}).then(()=>tx('draft','readwrite',s=>snapshot?s.put(snapshot):s.delete('active')));saveChain.catch(()=>say('Could not save the active workout on this device.'));return saveChain;}
function previous(name){const candidates=sessions.flatMap(s=>s.exercises.filter(e=>e.name.toLowerCase()===name.toLowerCase()).map(e=>({date:s.date,created:s.created,sets:e.sets})));entries.filter(e=>e.type==='workout'&&e.exercise.toLowerCase()===name.toLowerCase()).forEach(e=>candidates.push({date:e.date,created:e.created,sets:Array.from({length:e.sets},()=>({kg:e.load,reps:e.reps}))}));return candidates.sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created)[0]?.sets||[];}
async function start(routine){if(!db)return;if(active){tab('training');renderTraining();return;}active={id:'active',sessionId:uid(),name:routine?.name||'My workout',date:today(),created:Date.now(),exercises:(routine?.exercises||[]).map(e=>({id:uid(),name:e.name,sets:e.sets.map(s=>({...s,done:false}))}))};try{await saveDraft();renderTraining();render();tab('training');}catch{say('Could not start workout.');}}
$('start').onclick=()=>start();$('close-session').onclick=()=>tab('today');
$('session-name').oninput=()=>{if(active){active.name=$('session-name').value;saveDraft();}};$('session-date').onchange=()=>{if(active){active.date=$('session-date').value;saveDraft();}};
function renderTraining(){if(!active)return;$('session-name').value=active.name;$('session-date').value=active.date;const host=$('exercise-list');host.replaceChildren();if(!active.exercises.length)host.append(node('p','Add your first exercise to get started.','empty'));active.exercises.forEach(e=>{const card=node('div',undefined,'card'),head=node('div',undefined,'exercise-head');head.append(node('h2',e.name),button('Remove','text',async()=>{if(!confirm('Remove this exercise from the active workout?'))return;active.exercises=active.exercises.filter(x=>x.id!==e.id);await saveDraft();renderTraining();}));card.append(head);const prev=previous(e.name);card.append(node('p',prev.length?`Previous: ${prev.map(s=>`${s.kg} kg × ${s.reps}`).join(' · ')}`:'First session for this exercise.','hint'));const labels=node('div',undefined,'set-grid');['SET','KG','REPS','DONE'].forEach(t=>labels.append(node('small',t)));card.append(labels);e.sets.forEach((s,i)=>{const row=node('div',undefined,'set-grid');row.append(node('span',String(i+1)));for(const field of ['kg','reps']){const input=document.createElement('input');input.type='number';input.min=field==='kg'?'0':'1';input.max=field==='kg'?'1000':'1000';input.step=field==='kg'?'0.1':'1';input.inputMode=field==='kg'?'decimal':'numeric';input.value=s[field];input.setAttribute('aria-label',`${e.name} set ${i+1} ${field==='kg'?'kilograms':'repetitions'}`);input.oninput=()=>{s[field]=input.value===''?null:Number(input.value);s.done=false;row.lastChild.setAttribute('aria-pressed','false');saveDraft();};row.append(input);}const done=button('✓','check',()=>{if(!validSet(s)){say('Enter a valid load and whole-number reps first.');return;}s.done=!s.done;done.setAttribute('aria-pressed',String(s.done));saveDraft();});done.setAttribute('aria-label',`${e.name} set ${i+1} complete`);done.setAttribute('aria-pressed',String(s.done));row.append(done);card.append(row);});const actions=node('div',undefined,'actions');actions.append(button('＋ Add set','text',()=>{const last=e.sets.at(-1)||prev[0]||{kg:0,reps:10};e.sets.push({kg:last.kg,reps:last.reps,done:false});saveDraft();renderTraining();}),button('Remove last set','text',()=>{if(e.sets.at(-1)?.done&&!confirm('Remove the completed last set?'))return;e.sets.pop();saveDraft();renderTraining();}));card.append(actions);host.append(card);});}
function validSet(s){return Number.isFinite(s.kg)&&s.kg>=0&&s.kg<=1000&&Number.isInteger(s.reps)&&s.reps>0&&s.reps<=1000;}
$('add-exercise').onclick=()=>{$('exercise-form').reset();$('exercise-dialog').showModal();};$('cancel-exercise').onclick=()=>$('exercise-dialog').close();
$('exercise-form').onsubmit=async ev=>{ev.preventDefault();const name=$('exercise-name').value.trim();if(!name)return;const prev=previous(name);active.exercises.push({id:uid(),name,sets:(prev.length?prev:[{kg:0,reps:10}]).map(s=>({kg:s.kg,reps:s.reps,done:false}))});await saveDraft();$('exercise-dialog').close();renderTraining();};
$('finish').onclick=async()=>{if(!active)return;const exercises=active.exercises.map(e=>({...e,sets:e.sets.filter(s=>s.done&&validSet(s))})).filter(e=>e.sets.length);if(!exercises.length){say('Complete at least one set before finishing.');return;}if(!active.date){say('Choose a workout date.');return;}if(active.exercises.some(e=>e.sets.some(s=>!s.done))&&!confirm('Finish with completed sets only? Unchecked sets will not be recorded.'))return;$('finish').disabled=true;try{await saveChain;await tx('sessions','readwrite',s=>s.put({...active,id:active.sessionId,name:active.name.trim()||'My workout',exercises}));active=null;await saveDraft();await refresh();tab('history');say('Workout saved.');}catch{say('Could not finish saving. Your workout is retained locally; try again.');}finally{$('finish').disabled=false;}};
$('discard').onclick=async()=>{if(!confirm('Discard the active workout?'))return;active=null;try{await saveDraft();render();tab('today');say('Workout discarded.');}catch{say('Could not discard the workout.');}};
async function saveRoutine(){if(!active?.exercises.length){say('Add exercises first.');return;}const name=prompt('Routine name',active.name||'My routine');if(!name?.trim())return;const exercises=active.exercises.map(e=>({name:e.name,sets:e.sets.filter(validSet).map(s=>({kg:s.kg,reps:s.reps}))}));if(exercises.some(e=>!e.sets.length)){say('Each exercise needs at least one valid set.');return;}try{await tx('routines','readwrite',s=>s.put({id:uid(),name:name.trim().slice(0,100),exercises}));await refresh();say('Routine saved.');}catch{say('Could not save routine.');}}
$('save-routine').onclick=saveRoutine;$('new-routine').onclick=async()=>{await start();say('Add exercises and sets, then tap “Save exercises as a routine”.');};
function weightReset(){$('weight-form').reset();$('weight-date').value=today();weightEdit=null;$('cancel-weight').hidden=true;}
$('cancel-weight').onclick=weightReset;
$('weight-form').onsubmit=async ev=>{ev.preventDefault();if(!db)return;const value=Number($('weight-value').value);if(!Number.isFinite(value)||value<1||value>500)return;const old=entries.find(e=>e.id===weightEdit);try{await tx('entries','readwrite',s=>s.put({id:weightEdit||uid(),type:'weight',date:$('weight-date').value,value,note:$('weight-note').value.trim(),created:old?.created||Date.now()}));weightReset();await refresh();say('Weight saved.');}catch{say('Could not save weight.');}};
function formatDate(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function empty(host,text){host.append(node('p',text,'empty'));}
function render(){const weights=entries.filter(e=>e.type==='weight').sort((a,b)=>a.date.localeCompare(b.date)||a.created-b.created),latest=weights.at(-1);$('latest').textContent=latest?`${latest.value.toFixed(1)} kg`:'—';$('chart-weight').textContent=$('latest').textContent;const delta=latest&&weights.length>1?latest.value-weights[0].value:null;$('weight-change').textContent=delta===null?'No comparison yet':`${delta>0?'+':''}${delta.toFixed(1)} kg since first entry`;const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));$('workout-count').textContent=sessions.filter(s=>new Date(s.date+'T12:00:00')>=d&&s.date<=today()).length;$('start').textContent=active?'Resume workout':'＋ Start workout';const rh=$('routines');rh.replaceChildren();if(!routines.length)empty(rh,'Save a routine to make your next workout faster.');routines.forEach(r=>{const card=node('div',undefined,'card routine'),info=node('div');info.append(node('strong',r.name),node('small',`${r.exercises.length} exercises · ${r.exercises.reduce((n,e)=>n+e.sets.length,0)} sets`));card.append(info,button('Start','secondary',()=>start(r)),button('×','text',async()=>{if(!confirm(`Delete routine “${r.name}”?`))return;await tx('routines','readwrite',s=>s.delete(r.id));await refresh();}));rh.append(card);});renderHistory();chart(weights);renderBests();}
function renderHistory(){const host=$('history-list');host.replaceChildren();const filter=$('filter').value,items=[...entries,...sessions.map(s=>({...s,type:'session'}))].filter(r=>filter==='all'||r.type===filter).sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created);if(!items.length)empty(host,'Your logged progress will appear here.');items.forEach(r=>{const card=node('div',undefined,'card');card.append(node('strong',r.type==='weight'?`${r.value.toFixed(1)} kg`:r.type==='session'?r.name:r.exercise,'entry-title'),node('p',formatDate(r.date),'details'));if(r.type==='session')r.exercises.forEach(e=>card.append(node('p',`${e.name}: ${e.sets.map(s=>`${s.kg} kg × ${s.reps}`).join(' · ')}`,'details')));else if(r.type==='workout')card.append(node('p',`${r.sets} × ${r.reps} · ${r.load} kg`,'details'));if(r.note)card.append(node('p',r.note,'details'));const actions=node('div',undefined,'actions');if(r.type==='weight')actions.append(button('Edit','text',()=>{weightEdit=r.id;$('weight-date').value=r.date;$('weight-value').value=r.value;$('weight-note').value=r.note||'';$('cancel-weight').hidden=false;tab('today');$('weight-value').focus();}));if(r.type==='session')actions.append(button('Edit','text',async()=>{if(active){say('Finish or discard your active workout before editing another.');return;}active={...structuredClone(r),id:'active',sessionId:r.id};await saveDraft();render();renderTraining();tab('training');}));actions.append(button('Delete','danger',async()=>{if(!confirm('Delete this entry?'))return;try{if(active?.sessionId===r.id){say('Finish or discard this workout before deleting its saved entry.');return;}await tx(r.type==='session'?'sessions':'entries','readwrite',s=>s.delete(r.id));if(weightEdit===r.id)weightReset();await refresh();say('Entry deleted.');}catch{say('Could not delete entry.');}}));card.append(actions);host.append(card);});}
function renderBests(){const map=new Map();function add(name,kg,reps){const key=name.toLowerCase();if(reps>0&&(!map.has(key)||kg>map.get(key).kg))map.set(key,{name,kg});}entries.filter(e=>e.type==='workout').forEach(e=>add(e.exercise,e.load,e.reps));sessions.forEach(s=>s.exercises.forEach(e=>e.sets.forEach(x=>add(e.name,x.kg,x.reps))));const host=$('bests');host.replaceChildren();if(!map.size)empty(host,'Log a workout to start tracking your best lifts.');[...map.values()].sort((a,b)=>a.name.localeCompare(b.name)).forEach(r=>{const card=node('div',undefined,'card routine');card.append(node('strong',r.name),node('strong',`${r.kg} kg`));host.append(card);});}
function chart(weights){const host=$('chart');host.replaceChildren();if(weights.length<2){empty(host,'Add two weight entries to see your trend.');return;}const data=weights.slice(-30),min=Math.min(...data.map(r=>r.value))-.5,max=Math.max(...data.map(r=>r.value))+.5,times=data.map(r=>new Date(r.date+'T12:00:00').getTime()),range=times.at(-1)-times[0],points=data.map((r,i)=>[35+(range?(times[i]-times[0])/range:i/(data.length-1))*330,135-(r.value-min)/(max-min)*110]);const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 400 180');svg.setAttribute('role','img');svg.setAttribute('aria-label','Weight trend for your last 30 entries');const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.map(p=>p.join(',')).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#d2f574');line.setAttribute('stroke-width','3');svg.append(line);points.forEach(([x,y])=>{const c=document.createElementNS(ns,'circle');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r','3');c.setAttribute('fill','#d2f574');svg.append(c)});[[`${max.toFixed(1)}`,3,18],[`${min.toFixed(1)}`,3,150],[data[0].date,35,170],[data.at(-1).date,290,170]].forEach(([v,x,y])=>{const t=document.createElementNS(ns,'text');t.textContent=v;t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('fill','#929b93');t.setAttribute('font-size','11');svg.append(t)});host.append(svg);}
$('filter').onchange=renderHistory;$('today-date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}).toUpperCase();weightReset();
const open=indexedDB.open('my-fitness',2);open.onupgradeneeded=()=>{const database=open.result;for(const store of ['entries','sessions','routines','draft'])if(!database.objectStoreNames.contains(store))database.createObjectStore(store,{keyPath:'id'});};open.onsuccess=async()=>{db=open.result;db.onversionchange=()=>{db.close();say('The app was updated. Close and reopen it.');};try{active=(await all('draft'))[0]||null;await refresh();if(active)renderTraining();}catch{say('Could not read your local records.');}};open.onerror=()=>say('Local storage unavailable. Open in Safari or from your Home Screen.');open.onblocked=()=>say('Close other My Fitness tabs and reopen to complete the update.');
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js?v=3').catch(()=>say('Offline setup unavailable; online use still works.'));
